spring:
  application:
    name: API_project_backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api
    username: root
    password: 12345678
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0
server:
  port: 7529
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#在还没撰写数据库查询ak，sk逻辑前的测试用
#api:
#  client:
#    access-key: api
#    secretkey: 12345678

#以下配置指定了应用的名称、使用的协议(Dubbo)、注册中心的类型(Nacos)和地址
dubbo:
  scan:
    base-packages: com.api.project.provider, com.api.project.service.impl.inner
  application:
    #设置应用的名称
    name: dubbo-springboot-demo-provider
  #指定使用dubbo协议，且端口设置为-1，表示随机分配可用端口
  protocol:
    name: dubbo
    prot: 22221
  registry:
    #配置注册中心为Nacos，使用的地址是nacos://localhost:8848
    id: nacos-registry
    address: nacos://localhost:8848
cos:
  client:
    accessKey: AKIDdWI2YK1Vt7SlCoOr8BJJMNVYnxueSVXT
    secretKey: 0woaM2qiXUQAmIi3V5mPtKoTOWj4Rp8N
    region: ap-shanghai
    bucket: api-1321025141

