server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        #定义了一个名为"api route"的路由规则，该规则将匹配以"/api/"开头的路径，例如"/api/user",
        #并将这些请求转发到"http://1oca1host:8123"这个目标地址
        - id: path_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

#以下配置指定了应用的名称、使用的协议(Dubbo)、注册中心的类型(Nacos)和地址
dubbo:
  application:
    #设置应用的名称
    name: dubbo-springboot-demo-consumer
  #指定使用dubbo协议，且端口设置为-1，表示随机分配可用端口
  protocol:
    name: dubbo
    prot: 22223
  registry:
    #配置注册中心为Nacos，使用的地址是nacos://localhost:8848
    id: nacos-registry-nacos
    address: nacos://localhost:8848

